# This is a basic workflow that is manually triggered

name: stage the app
# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  pull_request:
    types: [labeled]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    if: contains(github.even.pull_request.labels.*.name, 'stage')
